const actions = {
  SET_ERROR: "SET_ERROR",
  RESET_ERROR: "RESET_ERROR",
  SET_LOADING: "SET_LOADING",
  RESET_LOADING: "RESET_LOADING",
  SET_BALANCE: "SET_BALANCE",
  SET_GUARDIANS: "SET_GUARDIANS",
  SET_TOKENS: "SET_TOKENS",
};

export default actions;
